# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "TwitterClient" do
    pod "AFNetworking"
    pod "MBProgressHUD"
    pod "BDBOAuth1Manager"
end

target "TwitterClientTests" do

end

